version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    environment:
      - "SPOTIPY_CLIENT_SECRET=${SPOTIPY_CLIENT_SECRET}"
      - "SPOTIPY_CLIENT_ID=${SPOTIPY_CLIENT_ID}"
    ports:
      - 5001:8081

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - 5000:5000
    depends_on:
      - backend
