version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - 5001:5000

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - 5000:5000
    depends_on:
      - backend
