FROM python:3.6.1

# set working directory
RUN mkdir -p /usr/src
WORKDIR /usr/src

# add requirements (to leverage Docker cache)
ADD ./requirements.txt ./requirements.txt

# install requirements
RUN pip install -r requirements.txt

# add app
ADD . .

# run server
CMD ["python", "src/serve.py"]
